kind: role
metadata:
  description: >-
    SSH login names. Doesn't grant access on its own — just says which
    usernames you can log in as. Always
    paired with one of the roles above (super-admin, cloud-admin-full-access,
    cloud-read-access).
  name: ssh-access
  revision: 5741978c-f798-46be-90cd-f77b2c14e6ba
spec:
  allow:
    logins:
    - customer
    - debendu
    - prod
    - rach
    node_labels:
      '*': '*'
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 12h0m0s
    pin_source_ip: false
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v7
